---

# Validate service on application master node

- name: Run pre tasks on master node
  hosts: appmaster  
  tasks:

  - name: Check AdminServer status on RUN filesystem
    become: yes
    become_method: sudo  
    become_user: "{{ oracle_user }}"
    shell: source {{ apps_env }} run; { echo {{ weblogic_pass }}; echo {{ apps_pass }}; } | sh $INST_TOP/admin/scripts/adadminsrvctl.sh status 
    register: check_adm_run_status

  - name: Start AdminServer on RUN filesystem
    become: yes
    become_method: sudo  
    become_user: "{{ oracle_user }}"
    shell: source {{ apps_env }} run; { echo {{ weblogic_pass }}; echo {{ apps_pass }}; } | sh $INST_TOP/admin/scripts/adadminsrvctl.sh start
    failed_when: start_adm_run.rc != 0
    register: start_adm_run
    when: "'The AdminServer is not running' in check_adm_run_status.stdout"

  - name: Check AdminServer status on PATCH filesystem
    become: yes
    become_method: sudo  
    become_user: "{{ oracle_user }}"
    shell: source {{ apps_env }} patch; { echo {{ weblogic_pass }}; echo {{ apps_pass }}; } | sh $INST_TOP/admin/scripts/adadminsrvctl.sh status
    register: check_adm_patch_status

  - name: Start AdminServer on PATCH filesystem
    become: yes
    become_method: sudo  
    become_user: "{{ oracle_user }}"
    shell: source {{ apps_env }} patch; { echo {{ weblogic_pass }}; echo {{ apps_pass }}; } | sh $INST_TOP/admin/scripts/adadminsrvctl.sh start forcepatchfs
    failed_when: start_adm_patch.rc != 0
    register: start_adm_patch
    when: "'The AdminServer is not running' in check_adm_patch_status.stdout"